


./AU-Tum_lclai_defa.csh
./US-KS2_lclai_defa.csh
./DK-Lva_lclai_defa.csh
./US-Goo_lclai_defa.csh
./US-MOz_lclai_defa.csh
./US-GLE_lclai_defa.csh
./IT-Cpz_lclai_defa.csh
./BE-Vie_lclai_defa.csh
./CA-SF3_lclai_defa.csh
./BE-Bra_lclai_defa.csh




./AU-Tum_lclai.csh
./US-KS2_lclai.csh
./DK-Lva_lclai.csh
./US-Goo_lclai.csh
./US-MOz_lclai.csh
./US-GLE_lclai.csh
./IT-Cpz_lclai.csh
./BE-Vie_lclai.csh
./CA-SF3_lclai.csh
./BE-Bra_lclai.csh



