
./IT-Cpz_pfth_defa.csh
./AU-How_pfth_defa.csh
./AU-DaS_pfth_defa.csh
./BE-Vie_pfth_defa.csh
./AU-Lit_pfth_defa.csh
./DE-Hai_pfth_defa.csh
./IT-Ren_pfth_defa.csh
./DE-Tha_pfth_defa.csh
./CA-SF1_pfth_defa.csh
./IT-Lav_pfth_defa.csh








./IT-Cpz_pfth.csh
./AU-How_pfth.csh
./AU-DaS_pfth.csh
./BE-Vie_pfth.csh
./AU-Lit_pfth.csh
./DE-Hai_pfth.csh
./IT-Ren_pfth.csh
./DE-Tha_pfth.csh
./CA-SF1_pfth.csh
./IT-Lav_pfth.csh 


